### ISSUE TITLE
Changing "go " keyword

### ISSUE THREAD

**Issue by alikorkmaz** [sasikanth513/keyword-redirect#1]
Hi, i like your extension so much, but i am looking for just a more feature.

Instead of typing "go " (g+o+space), i want to type something like "qq" (without space) to activate extension.

Can you let us specify this keyword in settings panel?

Thanks!

**Comment by ax4** [comment]
Hi, @alikorkmaz 

I share the same question with you. But before we enter more technical details, I would like to thank @sasikanth513 for his awesome work of this Keyword Redirect project! And I should also thank him so much that he made this extension open source on GitHub. It allows users to easily read source code, and it also turns out to be a good learning resource about how chrome and chrome extension work. Quote his saying: 
> Source code: Developed using vue.js with single component, should be easy to understand.

And the code is really easy to understand! Thanks @sasikanth513 ! 

I've been using Keyword Redirect for more than 6 months, since about November or December of 2019. And I've created my Todo list planning updates about this project on Dec 19, 2019. At that time, I was planning to clone and fork this repository, and bring up some possible fixes via Pull Request. But unfortunately, we all knows about this COVID-19 global crisis, and it really brings a breakdown to many people’s living (and losing life, sadly). This mental stressfulness paused my plan to code and to suggest some change. But anyway, we shall never lose hope. And I wish people’s living will get better and recovered after this pandemic (Bless to those who read and will read about this github comment).

So back to your question about the keyword “go”, where we put the word “go” in address bar, and enter “space / Tabs” after this action. This ability of user experience defined by chromium community is called [omnibox](https://www.chromium.org/user-experience/omnibox), and their design philosophy is about, quote: 
> The purpose of Chromium ’s omnibox is to merge both location and search fields while offering the user some highly relevant suggestions and / or early results.

However, from my experience, because chrome doesn’t “remember” so well about my early results (URLs, in terms of not invading privacy and browsing history) but in fact, I remember the URLs much better than chrome does. So there is a niche (or often called specific need, see [niche market](https://en.wikipedia.org/wiki/Niche_market)) about hard coding some frequent visiting keywords, linked to URLs, where it brings good omnibox experience with some manual fix. This is how I believe, Keyword Redirect, as a niche solution, does very well at it! 

Then we dive into the code, this line of code in `manifest.json` defines the trigger word of omnibox ability:  
https://github.com/sasikanth513/keyword-redirect/blob/263d553856c70930aaa19e1a3bb1d49057b9a784/manifest.json#L10 

But the limit of `manifest.json` is that, omnibox attribute is hard compiled as Chrome Web Store delivers only `.crx` file. So this makes monibox attribute, i.e. the monibox keyword unchangable by any configuration. I am happy to explore the extension dev document, to see how configuration works, although it may not come in a straightforward way. 
 
And as Dev.Opera’s blog suggests, Creating Address Bar Extensions: https://dev.opera.com/extensions/omnibox/ this should be easy to configure, if you knows how to load an unpacked extensions in chrome. 

But if you won’t like to risk “unpacked”, it's okay! Stay updated with this awesome Keyword Redirect extension from Chrome Store. I think I will come with some PR (pull request) to suggest some code change.

**Comment by sasikanth513** [comment]
Hi @ax4 thanks for the detailed explanation. Really appreciate this.

@alikorkmaz This is currently not possible with the API provided by chrome.

You'll have to clone the code and change it yourself like @ax4 mentioned. Let me know if I can be of any other help.
